/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CartRouteImport } from './routes/cart'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as CartSplatRouteImport } from './routes/cart.$'
import { Route as LangVideosRouteImport } from './routes/$lang/videos'
import { Route as LangToulouseRouteImport } from './routes/$lang/toulouse'
import { Route as LangSavRouteImport } from './routes/$lang/sav'
import { Route as LangPiecesRouteImport } from './routes/$lang/pieces'
import { Route as LangMotosRouteImport } from './routes/$lang/motos'
import { Route as LangMecaniqueRouteImport } from './routes/$lang/mecanique'
import { Route as LangLocationRouteImport } from './routes/$lang/location'
import { Route as LangLeucateRouteImport } from './routes/$lang/leucate'
import { Route as LangBarceloneRouteImport } from './routes/$lang/barcelone'
import { Route as LangB2bRouteImport } from './routes/$lang/b2b'
import { Route as LangAProposRouteImport } from './routes/$lang/a-propos'
import { Route as LangProductHandleRouteImport } from './routes/$lang/product.$handle'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const CartSplatRoute = CartSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => CartRoute,
} as any)
const LangVideosRoute = LangVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => LangRoute,
} as any)
const LangToulouseRoute = LangToulouseRouteImport.update({
  id: '/toulouse',
  path: '/toulouse',
  getParentRoute: () => LangRoute,
} as any)
const LangSavRoute = LangSavRouteImport.update({
  id: '/sav',
  path: '/sav',
  getParentRoute: () => LangRoute,
} as any)
const LangPiecesRoute = LangPiecesRouteImport.update({
  id: '/pieces',
  path: '/pieces',
  getParentRoute: () => LangRoute,
} as any)
const LangMotosRoute = LangMotosRouteImport.update({
  id: '/motos',
  path: '/motos',
  getParentRoute: () => LangRoute,
} as any)
const LangMecaniqueRoute = LangMecaniqueRouteImport.update({
  id: '/mecanique',
  path: '/mecanique',
  getParentRoute: () => LangRoute,
} as any)
const LangLocationRoute = LangLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => LangRoute,
} as any)
const LangLeucateRoute = LangLeucateRouteImport.update({
  id: '/leucate',
  path: '/leucate',
  getParentRoute: () => LangRoute,
} as any)
const LangBarceloneRoute = LangBarceloneRouteImport.update({
  id: '/barcelone',
  path: '/barcelone',
  getParentRoute: () => LangRoute,
} as any)
const LangB2bRoute = LangB2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => LangRoute,
} as any)
const LangAProposRoute = LangAProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => LangRoute,
} as any)
const LangProductHandleRoute = LangProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/cart': typeof CartRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/a-propos': typeof LangAProposRoute
  '/$lang/b2b': typeof LangB2bRoute
  '/$lang/barcelone': typeof LangBarceloneRoute
  '/$lang/leucate': typeof LangLeucateRoute
  '/$lang/location': typeof LangLocationRoute
  '/$lang/mecanique': typeof LangMecaniqueRoute
  '/$lang/motos': typeof LangMotosRoute
  '/$lang/pieces': typeof LangPiecesRoute
  '/$lang/sav': typeof LangSavRoute
  '/$lang/toulouse': typeof LangToulouseRoute
  '/$lang/videos': typeof LangVideosRoute
  '/cart/$': typeof CartSplatRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/product/$handle': typeof LangProductHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/a-propos': typeof LangAProposRoute
  '/$lang/b2b': typeof LangB2bRoute
  '/$lang/barcelone': typeof LangBarceloneRoute
  '/$lang/leucate': typeof LangLeucateRoute
  '/$lang/location': typeof LangLocationRoute
  '/$lang/mecanique': typeof LangMecaniqueRoute
  '/$lang/motos': typeof LangMotosRoute
  '/$lang/pieces': typeof LangPiecesRoute
  '/$lang/sav': typeof LangSavRoute
  '/$lang/toulouse': typeof LangToulouseRoute
  '/$lang/videos': typeof LangVideosRoute
  '/cart/$': typeof CartSplatRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/product/$handle': typeof LangProductHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/cart': typeof CartRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/a-propos': typeof LangAProposRoute
  '/$lang/b2b': typeof LangB2bRoute
  '/$lang/barcelone': typeof LangBarceloneRoute
  '/$lang/leucate': typeof LangLeucateRoute
  '/$lang/location': typeof LangLocationRoute
  '/$lang/mecanique': typeof LangMecaniqueRoute
  '/$lang/motos': typeof LangMotosRoute
  '/$lang/pieces': typeof LangPiecesRoute
  '/$lang/sav': typeof LangSavRoute
  '/$lang/toulouse': typeof LangToulouseRoute
  '/$lang/videos': typeof LangVideosRoute
  '/cart/$': typeof CartSplatRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/product/$handle': typeof LangProductHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/cart'
    | '/sitemap.xml'
    | '/$lang/a-propos'
    | '/$lang/b2b'
    | '/$lang/barcelone'
    | '/$lang/leucate'
    | '/$lang/location'
    | '/$lang/mecanique'
    | '/$lang/motos'
    | '/$lang/pieces'
    | '/$lang/sav'
    | '/$lang/toulouse'
    | '/$lang/videos'
    | '/cart/$'
    | '/$lang/'
    | '/$lang/product/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/sitemap.xml'
    | '/$lang/a-propos'
    | '/$lang/b2b'
    | '/$lang/barcelone'
    | '/$lang/leucate'
    | '/$lang/location'
    | '/$lang/mecanique'
    | '/$lang/motos'
    | '/$lang/pieces'
    | '/$lang/sav'
    | '/$lang/toulouse'
    | '/$lang/videos'
    | '/cart/$'
    | '/$lang'
    | '/$lang/product/$handle'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/cart'
    | '/sitemap.xml'
    | '/$lang/a-propos'
    | '/$lang/b2b'
    | '/$lang/barcelone'
    | '/$lang/leucate'
    | '/$lang/location'
    | '/$lang/mecanique'
    | '/$lang/motos'
    | '/$lang/pieces'
    | '/$lang/sav'
    | '/$lang/toulouse'
    | '/$lang/videos'
    | '/cart/$'
    | '/$lang/'
    | '/$lang/product/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  CartRoute: typeof CartRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/cart/$': {
      id: '/cart/$'
      path: '/$'
      fullPath: '/cart/$'
      preLoaderRoute: typeof CartSplatRouteImport
      parentRoute: typeof CartRoute
    }
    '/$lang/videos': {
      id: '/$lang/videos'
      path: '/videos'
      fullPath: '/$lang/videos'
      preLoaderRoute: typeof LangVideosRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/toulouse': {
      id: '/$lang/toulouse'
      path: '/toulouse'
      fullPath: '/$lang/toulouse'
      preLoaderRoute: typeof LangToulouseRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/sav': {
      id: '/$lang/sav'
      path: '/sav'
      fullPath: '/$lang/sav'
      preLoaderRoute: typeof LangSavRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/pieces': {
      id: '/$lang/pieces'
      path: '/pieces'
      fullPath: '/$lang/pieces'
      preLoaderRoute: typeof LangPiecesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/motos': {
      id: '/$lang/motos'
      path: '/motos'
      fullPath: '/$lang/motos'
      preLoaderRoute: typeof LangMotosRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/mecanique': {
      id: '/$lang/mecanique'
      path: '/mecanique'
      fullPath: '/$lang/mecanique'
      preLoaderRoute: typeof LangMecaniqueRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/location': {
      id: '/$lang/location'
      path: '/location'
      fullPath: '/$lang/location'
      preLoaderRoute: typeof LangLocationRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/leucate': {
      id: '/$lang/leucate'
      path: '/leucate'
      fullPath: '/$lang/leucate'
      preLoaderRoute: typeof LangLeucateRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/barcelone': {
      id: '/$lang/barcelone'
      path: '/barcelone'
      fullPath: '/$lang/barcelone'
      preLoaderRoute: typeof LangBarceloneRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/b2b': {
      id: '/$lang/b2b'
      path: '/b2b'
      fullPath: '/$lang/b2b'
      preLoaderRoute: typeof LangB2bRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/a-propos': {
      id: '/$lang/a-propos'
      path: '/a-propos'
      fullPath: '/$lang/a-propos'
      preLoaderRoute: typeof LangAProposRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/product/$handle': {
      id: '/$lang/product/$handle'
      path: '/product/$handle'
      fullPath: '/$lang/product/$handle'
      preLoaderRoute: typeof LangProductHandleRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangAProposRoute: typeof LangAProposRoute
  LangB2bRoute: typeof LangB2bRoute
  LangBarceloneRoute: typeof LangBarceloneRoute
  LangLeucateRoute: typeof LangLeucateRoute
  LangLocationRoute: typeof LangLocationRoute
  LangMecaniqueRoute: typeof LangMecaniqueRoute
  LangMotosRoute: typeof LangMotosRoute
  LangPiecesRoute: typeof LangPiecesRoute
  LangSavRoute: typeof LangSavRoute
  LangToulouseRoute: typeof LangToulouseRoute
  LangVideosRoute: typeof LangVideosRoute
  LangIndexRoute: typeof LangIndexRoute
  LangProductHandleRoute: typeof LangProductHandleRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAProposRoute: LangAProposRoute,
  LangB2bRoute: LangB2bRoute,
  LangBarceloneRoute: LangBarceloneRoute,
  LangLeucateRoute: LangLeucateRoute,
  LangLocationRoute: LangLocationRoute,
  LangMecaniqueRoute: LangMecaniqueRoute,
  LangMotosRoute: LangMotosRoute,
  LangPiecesRoute: LangPiecesRoute,
  LangSavRoute: LangSavRoute,
  LangToulouseRoute: LangToulouseRoute,
  LangVideosRoute: LangVideosRoute,
  LangIndexRoute: LangIndexRoute,
  LangProductHandleRoute: LangProductHandleRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

interface CartRouteChildren {
  CartSplatRoute: typeof CartSplatRoute
}

const CartRouteChildren: CartRouteChildren = {
  CartSplatRoute: CartSplatRoute,
}

const CartRouteWithChildren = CartRoute._addFileChildren(CartRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  CartRoute: CartRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()


